// Catalogo esplicito per la Console HP: include soltanto incantesimi che
// producono davvero un tiro salvezza su più creature o in un'area.
// Non usare areaCandidate come fonte di verità: può descrivere anche luce,
// portata o effetti secondari di spell a bersaglio singolo.
export const AREA_SAVE_SPELL_IDS = Object.freeze([
  "antipathy-sympathy",
  "black-tentacles",
  "blade-barrier",
  "burning-hands",
  "call-lightning",
  "calm-emotions",
  "circle-of-death",
  "cloudkill",
  "cone-of-cold",
  "confusion",
  "control-water",
  "delayed-blast-fireball",
  "earthquake",
  "entangle",
  "faerie-fire",
  "fear",
  "fire-storm",
  "fireball",
  "flame-strike",
  "freezing-sphere",
  "grease",
  "guardian-of-faith",
  "gust-of-wind",
  "hypnotic-pattern",
  "ice-storm",
  "incendiary-cloud",
  "insect-plague",
  "lightning-bolt",
  "meteor-swarm",
  "moonbeam",
  "prismatic-spray",
  "prismatic-wall",
  "reverse-gravity",
  "shatter",
  "sleet-storm",
  "slow",
  "stinking-cloud",
  "storm-of-vengeance",
  "sunbeam",
  "sunburst",
  "symbol",
  "thunderwave",
  "wall-of-fire",
  "wall-of-ice",
  "wall-of-thorns",
  "web",
  "weird",
  "wind-wall",
  "zone-of-truth",
  "xanathar-alba",
  "xanathar-arma-sacra",
  "xanathar-collera-della-natura",
  "xanathar-coltello-di-ghiaccio",
  "xanathar-controllare-venti",
  "xanathar-creare-falo",
  "xanathar-diavoletto-di-polvere",
  "xanathar-drago-illusorio",
  "xanathar-eruzione-terrestre",
  "xanathar-fulgore-nauseante",
  "xanathar-maelstrom",
  "xanathar-minuscole-meteore-di-melf",
  "xanathar-muro-di-luce",
  "xanathar-onda-di-marea",
  "xanathar-orrido-avvizzimento-di-abi-dalzim",
  "xanathar-oscurita-della-follia",
  "xanathar-parola-radiosa",
  "xanathar-passo-del-tuono",
  "xanathar-pirotecnica",
  "xanathar-rombo-di-tuono",
  "xanathar-sciame-di-palle-di-neve-di-snilloc",
  "xanathar-scossa-sinaptica",
  "xanathar-scossa-tellurica",
  "xanathar-sfera-acquea",
  "xanathar-sfera-al-vetriolo",
  "xanathar-sfera-della-tempesta",
  "xanathar-soffio-del-drago",
  "xanathar-trasmutare-roccia",
  "xanathar-turbine",
  "xanathar-vampa-di-aganazzar",
  "tasha-miscela-caustica-di-tasha",
  "tasha-turbine-di-spade",
]);

export const AREA_SAVE_SPELL_ID_SET = new Set(AREA_SAVE_SPELL_IDS);

// Sono gli effetti già presenti nel catalogo generale che appartengono ai
// bersagli del TS. Gli altri effetti dello stesso spell possono appartenere
// al caster o all'oggetto sorgente e non vanno copiati sui bersagli dell'area.
export const AREA_SAVE_EFFECT_RULES = Object.freeze({
  "faerie-fire": Object.freeze({
    failedEffectIds: Object.freeze(["incoming-attack-advantage"]),
  }),
  "xanathar-pirotecnica": Object.freeze({
    choiceId: "fireworks",
    failedEffectIds: Object.freeze(["fireworks-blinded"]),
  }),
  "xanathar-scossa-sinaptica": Object.freeze({
    failedEffectIds: Object.freeze(["synaptic-static-penalty"]),
  }),
  "tasha-miscela-caustica-di-tasha": Object.freeze({
    failedEffectIds: Object.freeze(["caustic-acid"]),
  }),
});
