const freeze = (value) => {
  if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
  for (const child of Object.values(value)) freeze(child);
  return Object.freeze(value);
};

const damage = ({ formula, type, onSave = "none", baseSlot = 0, additionalPerSlotAbove = 0 }) => ({
  formula,
  type,
  onSave,
  ...(baseSlot > 0 ? { baseSlot } : {}),
  ...(additionalPerSlotAbove > 0 ? { additionalPerSlotAbove } : {}),
});

const HEAT_METAL_PENALTY_ACTION = freeze({
  kind: "condition",
  action: "apply",
  targetId: "$target",
  name: "Svant. attacchi e prove",
  options: {
    sourceId: "$source",
    parentEffectId: "",
    effectId: "heat-metal-penalty",
    effectKind: "debuff",
    effectDetail: "Svantaggio ai tiri per colpire e alle prove di caratteristica fino all'inizio del prossimo turno del caster.",
    expiry: {
      mode: "turn-start",
      actor: "source",
      remaining: 1,
      anchor: "next-turn",
    },
  },
});

const HEAT_METAL_CONSTITUTION_SAVE_EFFECT = freeze({
  id: "heat-metal-constitution-save",
  label: "TS Costituzione",
  detail: "Se il portatore non lascia cadere l'oggetto, effettua un TS Costituzione: solo un fallimento applica lo svantaggio.",
  parentEffectId: "",
  deferredEffects: [
    {
      id: "heat-metal-constitution-save",
      timing: "immediate",
      actor: "target",
      reminder: "Effettua un TS Costituzione: se fallisce, subisce svantaggio ai tiri per colpire e alle prove di caratteristica.",
      save: { ability: "con" },
      resolution: {
        outcomes: {
          passed: { mode: "none" },
          failed: { actions: [HEAT_METAL_PENALTY_ACTION] },
          immune: { mode: "none" },
        },
      },
    },
  ],
});

export const HEAT_METAL_DROP_CHOICE_EFFECT = freeze({
  id: "heat-metal-drop-choice",
  label: "Scelta oggetto",
  detail: "Dopo il danno, scegli se il portatore lascia cadere l'oggetto.",
  parentEffectId: "",
  deferredEffects: [
    {
      id: "heat-metal-drop-choice",
      timing: "immediate",
      actor: "target",
      reminder: "Scegli: lascia cadere l'oggetto oppure non può / non lascia.",
      resolution: {
        mode: "choice",
        choiceLabels: {
          passed: "Lascia cadere",
          failed: "Non può / non lascia",
        },
        outcomes: {
          passed: { mode: "none" },
          failed: {
            actions: [{
              kind: "condition",
              action: "apply",
              targetId: "$target",
              name: HEAT_METAL_CONSTITUTION_SAVE_EFFECT.label,
              options: {
                sourceId: "$source",
                parentEffectId: HEAT_METAL_CONSTITUTION_SAVE_EFFECT.parentEffectId,
                effectId: HEAT_METAL_CONSTITUTION_SAVE_EFFECT.id,
                effectDetail: HEAT_METAL_CONSTITUTION_SAVE_EFFECT.detail,
                deferredEffects: HEAT_METAL_CONSTITUTION_SAVE_EFFECT.deferredEffects,
              },
            }],
          },
        },
      },
    },
  ],
});

// Azioni ripetibili dopo il lancio. Il contratto è volutamente indipendente
// dalla Console HP: il pannello usa soltanto questa dichiarazione per
// esporre il comando e delega la risoluzione al popup dedicato.
export const SPELL_ACTIVE_RESOLUTION_ACTIONS = freeze({
  "eyebite": [
    {
      id: "eyebite-saved",
      label: "TS superato · immune a questo lancio",
      buttonLabel: "TS superato",
      detail: "Registra una creatura che ha superato il TS Saggezza: non potrà più essere bersagliata da questa istanza di Sguardo penetrante.",
      economy: "action",
      turnStartPrompt: true,
      showInOverview: true,
      availableAfterCast: true,
      resolutionKind: "single-save",
      manualSaveAtTable: true,
      assumedOutcome: "passed",
      subjectMode: "none",
      requiresTargets: false,
      requiresParentInstance: true,
      requiresZoneRoot: false,
      rangeOrigin: "caster",
      range: { value: 18, unit: "m" },
      maxTargets: 1,
      save: { ability: "wis", onSuccess: "none" },
      excludedTargetEffectIds: [
        "eyebite-resisted",
        "eyebite-asleep",
        "eyebite-panicked",
        "eyebite-sickened",
      ],
      successEffects: [
        {
          id: "eyebite-resisted",
          label: "Immune a Sguardo penetrante",
          detail: "Ha superato un TS contro questo lancio e non può più essere bersagliato finché la spell resta attiva.",
          expiry: { mode: "concentration" },
        },
      ],
    },
    {
      id: "eyebite-asleep",
      label: "Addormentato · Privo di sensi",
      buttonLabel: "Addormentato",
      detail: "Dopo il TS fallito al tavolo, applica Privo di sensi. Si risveglia se subisce danni o se viene svegliato con un'azione.",
      economy: "action",
      turnStartPrompt: true,
      showInOverview: true,
      availableAfterCast: true,
      resolutionKind: "single-save",
      manualSaveAtTable: true,
      assumedOutcome: "failed",
      subjectMode: "none",
      requiresTargets: false,
      requiresParentInstance: true,
      requiresZoneRoot: false,
      rangeOrigin: "caster",
      range: { value: 18, unit: "m" },
      maxTargets: 1,
      save: { ability: "wis", onSuccess: "none" },
      excludedTargetEffectIds: [
        "eyebite-resisted",
        "eyebite-asleep",
        "eyebite-panicked",
        "eyebite-sickened",
      ],
      failureEffects: [
        {
          id: "eyebite-asleep",
          label: "Privo di sensi",
          detail: "Si risveglia se subisce danni o se un'altra creatura usa un'azione per scuoterlo.",
          mechanics: { endsOnDamage: true },
          expiry: { mode: "concentration" },
          manualRemoval: true,
        },
      ],
    },
    {
      id: "eyebite-panicked",
      label: "In preda al panico · Spaventato",
      buttonLabel: "Panico",
      detail: "Dopo il TS fallito al tavolo, applica Spaventato. Nel suo turno deve Scattare e allontanarsi dal caster.",
      economy: "action",
      turnStartPrompt: true,
      showInOverview: true,
      availableAfterCast: true,
      resolutionKind: "single-save",
      manualSaveAtTable: true,
      assumedOutcome: "failed",
      subjectMode: "none",
      requiresTargets: false,
      requiresParentInstance: true,
      requiresZoneRoot: false,
      rangeOrigin: "caster",
      range: { value: 18, unit: "m" },
      maxTargets: 1,
      save: { ability: "wis", onSuccess: "none" },
      excludedTargetEffectIds: [
        "eyebite-resisted",
        "eyebite-asleep",
        "eyebite-panicked",
        "eyebite-sickened",
      ],
      failureEffects: [
        {
          id: "eyebite-panicked",
          label: "Spaventato",
          detail: "Deve usare Scatto e allontanarsi lungo il percorso più breve e sicuro. Rimuovi l'effetto quando è oltre 18 m e non vede più il caster.",
          expiry: { mode: "concentration" },
          manualRemoval: true,
          saveReminder: {
            timing: "turn-start",
            mode: "consume",
            label: "Deve usare Scatto e allontanarsi dal caster lungo il percorso più breve e sicuro possibile.",
          },
        },
      ],
    },
    {
      id: "eyebite-sickened",
      label: "Nauseato · svantaggio attacchi/prove",
      buttonLabel: "Nauseato",
      detail: "Dopo il TS fallito al tavolo, applica Nauseato. A fine turno ripete il TS Saggezza.",
      economy: "action",
      turnStartPrompt: true,
      showInOverview: true,
      availableAfterCast: true,
      resolutionKind: "single-save",
      manualSaveAtTable: true,
      assumedOutcome: "failed",
      subjectMode: "none",
      requiresTargets: false,
      requiresParentInstance: true,
      requiresZoneRoot: false,
      rangeOrigin: "caster",
      range: { value: 18, unit: "m" },
      maxTargets: 1,
      save: { ability: "wis", onSuccess: "none" },
      excludedTargetEffectIds: [
        "eyebite-resisted",
        "eyebite-asleep",
        "eyebite-panicked",
        "eyebite-sickened",
      ],
      failureEffects: [
        {
          id: "eyebite-sickened",
          label: "Nauseato",
          detail: "Svantaggio ai tiri per colpire e alle prove di caratteristica.",
          expiry: { mode: "concentration" },
          manualRemoval: true,
          saveReminder: {
            ability: "wis",
            timing: "turn-end",
            dcSource: "source-spell",
            label: "Se supera il TS Saggezza, termina Nauseato e non può più essere bersagliato da questo lancio.",
            resolution: {
              success: {
                mode: "remove-effect",
                actions: [{
                  kind: "condition",
                  action: "apply",
                  targetId: "$target",
                  parentEffectId: "$parent",
                  name: "Immune a Sguardo penetrante",
                  options: {
                    effectId: "eyebite-resisted",
                    type: "spell",
                    expiry: { mode: "concentration" },
                  },
                }],
              },
              failure: "keep-effect",
            },
          },
        },
      ],
    },
  ],
  "xanathar-corona-di-stelle": [
    {
      id: "crown-of-stars-launch",
      label: "Lancia una stella · 4d12 radiosi",
      buttonLabel: "Lancia una stella",
      detail: "Azione bonus: invia una stella verso una creatura entro 36 m. La stella viene consumata sia se colpisce sia se manca.",
      economy: "bonus-action",
      turnStartPrompt: true,
      showInOverview: true,
      availableAfterCast: true,
      resolutionKind: "single-attack",
      subjectMode: "none",
      requiresTargets: false,
      requiresParentInstance: true,
      requiresZoneRoot: false,
      rangeOrigin: "caster",
      range: { value: 36, unit: "m" },
      maxTargets: 1,
      attack: {
        outcomes: ["hit", "miss"],
        damageRequiredOnHitOnly: true,
      },
      damage: damage({ formula: "4d12", type: "radiosi" }),
      resource: { key: "stars", consume: 1, endSpellAtZero: true },
    },
  ],
  "xanathar-muro-di-luce": [
    {
      id: "wall-of-light-beam",
      label: "Raggio radioso · 4d8",
      buttonLabel: "Raggio radioso",
      detail: "Azione: effettua un attacco con incantesimo a distanza contro una creatura entro 18 m dal muro. Colpito: 4d8 radiosi. Colpito o mancato: il muro si accorcia di 3 m dall’estremità finale.",
      economy: "action",
      turnStartPrompt: true,
      showInOverview: true,
      availableAfterCast: true,
      resolutionKind: "single-attack",
      subjectMode: "none",
      requiresTargets: false,
      requiresParentInstance: true,
      requiresZoneRoot: true,
      rangeOrigin: "root",
      range: { value: 18, unit: "m" },
      rangeFromZoneArea: true,
      maxTargets: 1,
      attack: {
        outcomes: ["hit", "miss"],
        damageRequiredOnHitOnly: true,
      },
      damage: damage({
        formula: "4d8",
        type: "radiosi",
        onSave: "none",
        baseSlot: 5,
        additionalPerSlotAbove: 1,
      }),
      shortenStaticZone: {
        meters: 3,
        from: "end",
        chooseFrom: true,
        endSpellAtZero: true,
      },
    },
  ],
  "xanathar-debilitazione": [
    {
      id: "enervation-repeat",
      label: "Ripeti Debilitazione · danno necrotico",
      buttonLabel: "Ripeti Debilitazione",
      detail: "Azione: infliggi di nuovo il danno necrotico al bersaglio collegato. Il caster recupera automaticamente PF pari alla metà del danno necrotico finale inserito, già dopo eventuali resistenze.",
      economy: "action",
      turnStartPrompt: true,
      showInOverview: true,
      availableAfterCast: true,
      // Il popup single-save viene riusato in modalità manualSaveAtTable: l'esito
      // è fissato a Fallito e quindi non viene mostrato alcun nuovo TS.
      resolutionKind: "single-save",
      manualSaveAtTable: true,
      assumedOutcome: "failed",
      subjectMode: "none",
      requiresTargets: false,
      requiresParentInstance: true,
      requiresZoneRoot: false,
      rangeOrigin: "caster",
      range: { value: 18, unit: "m" },
      maxTargets: 1,
      save: { ability: "dex", onSuccess: "none" },
      damage: damage({
        formula: "4d8",
        type: "necrotici",
        onSave: "none",
        baseSlot: 5,
        additionalPerSlotAbove: 1,
      }),
      requiredTargetEffectId: "enervation-link",
      linkedTargetHint: "collegato a Debilitazione. La cura del caster è automatica: metà del danno necrotico finale inserito.",
      casterHealingFromAppliedDamage: 0.5,
    },
  ],
  "heat-metal": [
    {
      id: "heat-metal-repeat",
      label: "Ripeti calore",
      buttonLabel: "Ripeti calore",
      detail: "Azione bonus: infliggi 2d8 danni da fuoco; dopo il danno il portatore decide se lasciare cadere l'oggetto.",
      economy: "bonus-action",
      turnStartPrompt: true,
      showInOverview: true,
      availableAfterCast: true,
      resolutionKind: "single-save",
      subjectMode: "none",
      requiresTargets: false,
      requiresParentInstance: true,
      requiresZoneRoot: false,
      rangeOrigin: "caster",
      maxTargets: 1,
      rememberTargets: true,
      manualSaveAtTable: true,
      assumedOutcome: "passed",
      manualOutcomeLabel: "Danno",
      save: { ability: "con", onSuccess: "none" },
      damage: damage({
        formula: "2d8",
        type: "fuoco",
        onSave: "full",
        baseSlot: 2,
        additionalPerSlotAbove: 1,
      }),
      postDamageEffects: [HEAT_METAL_DROP_CHOICE_EFFECT],
    },
  ],
  "arcane-sword": [
    {
      id: "arcane-sword-attack",
      label: "Attacco · 3d10 forza",
      buttonLabel: "Attacco",
      detail: "Azione bonus: muovi la Spada arcana e risolvi un attacco contro una creatura entro 1,5 m.",
      economy: "bonus-action",
      resolutionKind: "single-attack",
      subjectMode: "none",
      requiresTargets: false,
      requiresParentInstance: true,
      requiresZoneRoot: true,
      rangeOrigin: "root",
      range: { value: 1.5, unit: "m" },
      maxTargets: 1,
      attack: { outcomes: ["hit", "miss"] },
      damage: damage({ formula: "3d10", type: "forza", baseSlot: 7 }),
    },
  ],
  "spiritual-weapon": [
    {
      id: "spiritual-weapon-attack",
      label: "Attacco · 1d8 + mod",
      buttonLabel: "Attacco",
      detail: "Azione bonus: muovi l'Arma spirituale e risolvi un attacco entro 1,5 m. Il modificatore resta manuale.",
      economy: "bonus-action",
      resolutionKind: "single-attack",
      subjectMode: "none",
      requiresTargets: false,
      requiresParentInstance: true,
      requiresZoneRoot: true,
      rangeOrigin: "root",
      range: { value: 1.5, unit: "m" },
      maxTargets: 1,
      attack: { outcomes: ["hit", "miss"] },
      damage: damage({
        formula: "1d8",
        type: "forza",
        baseSlot: 2,
        additionalPerSlotAbove: 1,
      }),
      damageScaling: { everySlotLevels: 2 },
    },
  ],
  "tasha-lama-del-disastro": [
    {
      id: "blade-of-disaster-attacks",
      label: "Fino a 2 attacchi · 4d12",
      buttonLabel: "Attacchi",
      detail: "Azione bonus: muovi la lama e risolvi fino a due attacchi entro 1,5 m. Un 18–20 è critico.",
      economy: "bonus-action",
      resolutionKind: "single-attack",
      subjectMode: "none",
      requiresTargets: false,
      requiresParentInstance: true,
      requiresZoneRoot: true,
      rangeOrigin: "root",
      range: { value: 1.5, unit: "m" },
      maxTargets: 1,
      maxAttacks: 2,
      attack: { outcomes: ["hit", "miss", "critical"] },
      damage: damage({ formula: "4d12", type: "forza", baseSlot: 9 }),
      critical: { minimumD20: 18, additionalDice: "8d12" },
    },
  ],
  "control-water": [
    {
      id: "control-water-whirlpool",
      label: "Crea Vortice",
      buttonLabel: "Vortice",
      detail: "Usa l'azione per posizionare un vortice di raggio 7,5 m dentro la zona di Controllare acqua.",
      economy: "action",
      resolutionKind: "child-zone",
      subjectMode: "none",
      requiresTargets: false,
      requiresZoneRoot: true,
      rangeOrigin: "root",
      range: { value: 30, unit: "m" },
      requiresParentInstance: true,
      placementRuleId: "control-water:whirlpool",
      childZone: {
        childKind: "whirlpool",
        placementRuleId: "control-water:whirlpool",
        placementCount: { min: 1, max: 1 },
        replaceChildKind: "whirlpool",
        ruleChoice: "whirlpool",
        resolution: "none",
      },
    },
  ],
  earthquake: [
    {
      id: "earthquake-fissures",
      label: "Crea Fessure",
      buttonLabel: "Fessure",
      detail: "Dal turno successivo al lancio, scegli da 1 a 6 fessure che attraversino la zona di Terremoto.",
      economy: "action",
      resolutionKind: "child-zone",
      subjectMode: "none",
      requiresTargets: false,
      requiresZoneRoot: true,
      rangeOrigin: "root",
      range: { value: 30, unit: "m" },
      requiresParentInstance: true,
      availableAfterCast: true,
      placementRuleId: "earthquake:fissure",
      childZone: {
        childKind: "fissure",
        placementRuleId: "earthquake:fissure",
        placementCount: { min: 1, max: 6 },
        singleActivation: true,
        resolution: "save",
        save: { ability: "dex" },
        depth: {
          label: "Profondità (d10)",
          min: 1,
          max: 10,
          multiplierMeters: 3,
        },
        failureEffect: {
          label: "Caduto nella fessura",
          detail: "Il bersaglio cade nella fessura; la gestione della profondità e dell'uscita resta manuale.",
          effectId: "earthquake-fissure-fall",
        },
      },
    },
  ],
  "phb2014-freccia-folgorante": [
    {
      id: "lightning-arrow-area",
      label: "Esplosione · danno area fulmine",
      buttonLabel: "Risolvi esplosione",
      detail: "Centra l'esplosione sul bersaglio dell'attacco già effettuato. Il danno primario resta applicato manualmente dal GM; qui si risolvono solo TS, danno area e consumo della preparazione.",
      economy: "bonus-action",
      resolutionKind: "save-area",
      subjectMode: "none",
      requiresTargets: false,
      requiresParentInstance: true,
      requiresZoneRoot: false,
      placementRuleId: "phb2014-freccia-folgorante:cast",
      rangeOrigin: "caster",
      areaAnchor: "primary-target",
      anchorTargetFromSelection: true,
      excludeAnchorTarget: true,
      allowEmptyTargets: true,
      damageRequiredWithTargetsOnly: true,
      save: { ability: "dex", onSuccess: "half" },
      damage: damage({
        formula: "2d8",
        type: "fulmine",
        onSave: "half",
        baseSlot: 3,
        additionalPerSlotAbove: 1,
      }),
      concentrationAction: "dismiss",
    },
  ],
  "call-lightning": [
    {
      id: "call-lightning-strike",
      label: "Richiama fulmine",
      buttonLabel: "Invoca fulmine",
      detail: "Azione: scegli il punto del fulmine e risolvi un TS Destrezza per le creature nella sagoma.",
      economy: "action",
      resolutionKind: "save-area",
      subjectMode: "none",
      requiresTargets: false,
      turnStartPrompt: true,
      showInOverview: true,
      placementRuleId: "call-lightning:cast",
      rangeOrigin: "caster",
      save: { ability: "dex", onSuccess: "half" },
      damage: damage({
        formula: "3d10",
        type: "fulmine",
        onSave: "half",
        baseSlot: 3,
        additionalPerSlotAbove: 1,
      }),
      naturalStormBonus: {
        formula: "1d10",
        type: "fulmine",
        label: "Bonus manuale per tempesta naturale",
      },
      requiresParentInstance: true,
    },
  ],
  "gust-of-wind": [
    {
      id: "gust-of-wind-direction",
      label: "Cambia direzione",
      buttonLabel: "Cambia direzione",
      detail: "Azione bonus: riorienta la Folata di Vento.",
      economy: "bonus-action",
      resolutionKind: "zone-direction",
      subjectMode: "none",
      requiresTargets: false,
      requiresParentInstance: true,
      requiresZoneRoot: true,
      availableAfterCast: true,
      showInOverview: true,
      placementRuleId: "gust-of-wind:cast",
      rangeOrigin: "caster",
    },
  ],
  "xanathar-investitura-del-vento": [
    {
      id: "wind-investiture-gust",
      label: "Cubo di vento",
      buttonLabel: "Cubo di vento",
      detail: "Azione: crea un cubo di vento di 4,5 m entro 18 m. TS Costituzione: 2d10 contundenti, metà se superato; una creatura Grande o inferiore che fallisce può essere spinta fino a 3 m lontano dal centro.",
      economy: "action",
      resolutionKind: "save-area",
      subjectMode: "none",
      requiresTargets: false,
      turnStartPrompt: true,
      showInOverview: true,
      availableAfterCast: true,
      placementRuleId: "xanathar-investitura-del-vento:cubo-di-vento",
      rangeOrigin: "caster",
      save: { ability: "con", onSuccess: "half" },
      damage: damage({
        formula: "2d10",
        type: "contundenti",
        onSave: "half",
      }),
      requiresParentInstance: true,
    },
  ],
  "xanathar-investitura-della-fiamma": [
    {
      id: "flame-investiture-line",
      label: "Linea di fuoco",
      buttonLabel: "Linea di fuoco",
      detail: "Azione: traccia una linea di fuoco lunga 4,5 m e larga 1,5 m adiacente al caster.",
      economy: "action",
      resolutionKind: "save-area",
      subjectMode: "none",
      requiresTargets: false,
      turnStartPrompt: true,
      showInOverview: true,
      availableAfterCast: true,
      placementRuleId: "xanathar-investitura-della-fiamma:linea-di-fuoco",
      rangeOrigin: "caster",
      save: { ability: "dex", onSuccess: "half" },
      damage: damage({
        formula: "4d8",
        type: "fuoco",
        onSave: "half",
      }),
      requiresParentInstance: true,
    },
  ],
  "xanathar-investitura-della-pietra": [
    {
      id: "stone-investiture-quake",
      label: "Scossa tellurica",
      buttonLabel: "Scossa tellurica",
      detail: "Azione: crea un piccolo terremoto sul terreno entro 4,5 m dal caster. Le altre creature effettuano un TS Destrezza; chi fallisce cade Prono.",
      economy: "action",
      resolutionKind: "save-area",
      subjectMode: "none",
      requiresTargets: false,
      turnStartPrompt: true,
      showInOverview: true,
      availableAfterCast: true,
      fixedCasterRadius: { value: 4.5, unit: "m", includeCaster: false },
      rangeOrigin: "caster",
      save: { ability: "dex", onSuccess: "none" },
      failureEffects: [
        {
          id: "stone-investiture-prone",
          label: "Prono",
          detail: "Caduto a terra per la scossa tellurica dell'Investitura della Pietra.",
          parentEffectId: "",
          expiry: { mode: "manual" },
          manualRemoval: true,
        },
      ],
      requiresParentInstance: true,
    },
  ],
  "xanathar-arma-sacra": [
    {
      id: "holy-weapon-dismiss",
      label: "Esplosione radiosa",
      buttonLabel: "Congeda Arma Sacra",
      detail: "Azione bonus: congeda l'arma e crea un'esplosione radiosa di raggio 9 m.",
      economy: "bonus-action",
      resolutionKind: "save-area",
      subjectMode: "none",
      requiresTargets: false,
      turnStartPrompt: true,
      showInOverview: true,
      requiresParentInstance: true,
      requiresZoneRoot: false,
      availableAfterCast: true,
      placementRuleId: "xanathar-arma-sacra:burst",
      rangeOrigin: "caster",
      save: { ability: "con", onSuccess: "half" },
      damage: damage({
        formula: "4d8",
        type: "radiosi",
        onSave: "half",
      }),
      concentrationAction: "dismiss",
      failureEffects: [
        {
          id: "holy-weapon-blinded",
          label: "Accecato",
          detail: "Accecato per 1 minuto. Alla fine di ogni turno, TS Costituzione per terminare l'effetto.",
          expiry: { mode: "rounds", remaining: 10 },
          parentEffectId: "",
          manualRemoval: true,
          saveReminder: {
            ability: "con",
            timing: "turn-end",
            dcSource: "source-spell",
            label: "Se supera il TS, termina Accecato su di sé.",
          },
        },
      ],
    },
  ],
  "xanathar-sfera-della-tempesta": [
    {
      id: "storm-sphere-lightning",
      label: "Fulmine",
      buttonLabel: "Fulmine",
      detail: "Azione bonus: scegli una creatura entro 18 m dal centro della Sfera della Tempesta.",
      economy: "bonus-action",
      resolutionKind: "single-attack",
      subjectMode: "none",
      requiresTargets: false,
      turnStartPrompt: true,
      requiresZoneRoot: true,
      rangeOrigin: "root",
      range: { value: 18, unit: "m" },
      maxTargets: 1,
      attack: {
        outcomes: ["hit", "miss"],
        advantageWhen: "inside-root",
      },
      damage: damage({
        formula: "4d6",
        type: "fulmine",
        baseSlot: 4,
        additionalPerSlotAbove: 1,
      }),
      requiresParentInstance: true,
    },
  ],
  "xanathar-stretta-della-terra-di-maximilian": [
    {
      id: "maximilian-earth-grasp-crush",
      label: "Stritola · 2d6 (metà se supera)",
      buttonLabel: "Stritola",
      detail: "Azione: il bersaglio attualmente trattenuto dalla mano effettua un TS Forza; subisce 2d6 contundenti, metà se supera.",
      economy: "action",
      turnStartPrompt: true,
      showInOverview: true,
      availableAfterCast: true,
      resolutionKind: "single-save",
      subjectMode: "none",
      requiresTargets: false,
      requiresParentInstance: true,
      requiresZoneRoot: false,
      rangeOrigin: "caster",
      maxTargets: 1,
      save: { ability: "str", onSuccess: "half" },
      damage: damage({ formula: "2d6", type: "contundenti", onSave: "half" }),
      requiredTargetEffectId: "maximilian-earth-grasp-restrained",
    },
    {
      id: "maximilian-earth-grasp-grab",
      label: "Afferra · Trattenuto",
      buttonLabel: "Afferra",
      detail: "Azione: dopo aver risolto il TS Forza al tavolo, scegli una creatura nella corona di 8 caselle attorno alla mano e applica Trattenuto.",
      economy: "action",
      turnStartPrompt: true,
      showInOverview: true,
      availableAfterCast: true,
      resolutionKind: "single-save",
      manualSaveAtTable: true,
      assumedOutcome: "failed",
      adjacentRing: true,
      subjectMode: "none",
      requiresTargets: false,
      requiresParentInstance: true,
      requiresZoneRoot: true,
      rangeOrigin: "root",
      range: { value: 1.5, unit: "m" },
      maxTargets: 1,
      save: { ability: "str", onSuccess: "none" },
      replaceLinkedEffectId: "maximilian-earth-grasp-restrained",
      excludedTargetEffectId: "maximilian-earth-grasp-restrained",
      failureEffects: [
        {
          id: "maximilian-earth-grasp-restrained",
          label: "Trattenuto",
          detail: "La mano di terra trattiene il bersaglio. Può usare un'azione per effettuare una prova di Forza contro la CD della spell e liberarsi.",
          expiry: { mode: "concentration" },
          manualRemoval: true,
        },
      ],
    },
  ],
});

export function getSpellActiveResolutionActions(spellId) {
  return SPELL_ACTIVE_RESOLUTION_ACTIONS[String(spellId || "").trim()] || [];
}
