const freeze = (value) => {
  if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
  for (const child of Object.values(value)) freeze(child);
  return Object.freeze(value);
};

const damage = ({ formula, type, onSave = "none", baseSlot = 0, additionalPerSlotAbove = 0 }) => ({
  formula,
  type,
  onSave,
  ...(baseSlot > 0 ? { baseSlot } : {}),
  ...(additionalPerSlotAbove > 0 ? { additionalPerSlotAbove } : {}),
});

// Azioni ripetibili dopo il lancio. Il contratto è volutamente indipendente
// dalla Console HP: il pannello usa soltanto questa dichiarazione per
// esporre il comando e delega la risoluzione al popup dedicato.
export const SPELL_ACTIVE_RESOLUTION_ACTIONS = freeze({
  "heat-metal": [
    {
      id: "heat-metal-repeat",
      label: "Ripeti calore Â· 2d8 fuoco",
      buttonLabel: "Ripeti calore",
      detail: "Risolvi il nuovo TS di Costituzione e applica, se necessario, lo svantaggio fino all'inizio del prossimo turno del caster.",
      economy: "action",
      resolutionKind: "single-attack",
      subjectMode: "none",
      requiresTargets: false,
      requiresParentInstance: true,
      requiresZoneRoot: false,
      rangeOrigin: "caster",
      maxTargets: 1,
      attack: { outcomes: ["hit", "miss"] },
      damage: damage({ formula: "2d8", type: "fuoco", baseSlot: 2 }),
      effectOn: "hit",
    },
  ],
  "arcane-sword": [
    {
      id: "arcane-sword-attack",
      label: "Attacco · 3d10 forza",
      buttonLabel: "Attacco",
      detail: "Azione bonus: muovi la Spada arcana e risolvi un attacco contro una creatura entro 1,5 m.",
      economy: "bonus-action",
      resolutionKind: "single-attack",
      subjectMode: "none",
      requiresTargets: false,
      requiresParentInstance: true,
      requiresZoneRoot: true,
      rangeOrigin: "root",
      range: { value: 1.5, unit: "m" },
      maxTargets: 1,
      attack: { outcomes: ["hit", "miss"] },
      damage: damage({ formula: "3d10", type: "forza", baseSlot: 7 }),
    },
  ],
  "spiritual-weapon": [
    {
      id: "spiritual-weapon-attack",
      label: "Attacco · 1d8 + mod",
      buttonLabel: "Attacco",
      detail: "Azione bonus: muovi l'Arma spirituale e risolvi un attacco entro 1,5 m. Il modificatore resta manuale.",
      economy: "bonus-action",
      resolutionKind: "single-attack",
      subjectMode: "none",
      requiresTargets: false,
      requiresParentInstance: true,
      requiresZoneRoot: true,
      rangeOrigin: "root",
      range: { value: 1.5, unit: "m" },
      maxTargets: 1,
      attack: { outcomes: ["hit", "miss"] },
      damage: damage({
        formula: "1d8",
        type: "forza",
        baseSlot: 2,
        additionalPerSlotAbove: 1,
      }),
      damageScaling: { everySlotLevels: 2 },
    },
  ],
  "tasha-lama-del-disastro": [
    {
      id: "blade-of-disaster-attacks",
      label: "Fino a 2 attacchi · 4d12",
      buttonLabel: "Attacchi",
      detail: "Azione bonus: muovi la lama e risolvi fino a due attacchi entro 1,5 m. Un 18–20 è critico.",
      economy: "bonus-action",
      resolutionKind: "single-attack",
      subjectMode: "none",
      requiresTargets: false,
      requiresParentInstance: true,
      requiresZoneRoot: true,
      rangeOrigin: "root",
      range: { value: 1.5, unit: "m" },
      maxTargets: 1,
      maxAttacks: 2,
      attack: { outcomes: ["hit", "miss", "critical"] },
      damage: damage({ formula: "4d12", type: "forza", baseSlot: 9 }),
      critical: { minimumD20: 18, additionalDice: "8d12" },
    },
  ],
  "control-water": [
    {
      id: "control-water-whirlpool",
      label: "Crea Vortice",
      buttonLabel: "Vortice",
      detail: "Usa l'azione per posizionare un vortice di raggio 7,5 m dentro la zona di Controllare acqua.",
      economy: "action",
      resolutionKind: "child-zone",
      subjectMode: "none",
      requiresTargets: false,
      requiresZoneRoot: true,
      rangeOrigin: "root",
      range: { value: 30, unit: "m" },
      requiresParentInstance: true,
      placementRuleId: "control-water:whirlpool",
      childZone: {
        childKind: "whirlpool",
        placementRuleId: "control-water:whirlpool",
        placementCount: { min: 1, max: 1 },
        replaceChildKind: "whirlpool",
        ruleChoice: "whirlpool",
        resolution: "none",
      },
    },
  ],
  earthquake: [
    {
      id: "earthquake-fissures",
      label: "Crea Fessure",
      buttonLabel: "Fessure",
      detail: "Dal turno successivo al lancio, scegli da 1 a 6 fessure che attraversino la zona di Terremoto.",
      economy: "action",
      resolutionKind: "child-zone",
      subjectMode: "none",
      requiresTargets: false,
      requiresZoneRoot: true,
      rangeOrigin: "root",
      range: { value: 30, unit: "m" },
      requiresParentInstance: true,
      availableAfterCast: true,
      placementRuleId: "earthquake:fissure",
      childZone: {
        childKind: "fissure",
        placementRuleId: "earthquake:fissure",
        placementCount: { min: 1, max: 6 },
        singleActivation: true,
        resolution: "save",
        save: { ability: "dex" },
        depth: {
          label: "Profondità (d10)",
          min: 1,
          max: 10,
          multiplierMeters: 3,
        },
        failureEffect: {
          label: "Caduto nella fessura",
          detail: "Il bersaglio cade nella fessura; la gestione della profondità e dell'uscita resta manuale.",
          effectId: "earthquake-fissure-fall",
        },
      },
    },
  ],
  "call-lightning": [
    {
      id: "call-lightning-strike",
      label: "Richiama fulmine",
      buttonLabel: "Invoca fulmine",
      detail: "Azione: scegli il punto del fulmine e risolvi un TS Destrezza per le creature nella sagoma.",
      economy: "action",
      resolutionKind: "save-area",
      subjectMode: "none",
      requiresTargets: false,
      turnStartPrompt: true,
      showInOverview: true,
      placementRuleId: "call-lightning:cast",
      rangeOrigin: "caster",
      save: { ability: "dex", onSuccess: "half" },
      damage: damage({
        formula: "3d10",
        type: "fulmine",
        onSave: "half",
        baseSlot: 3,
        additionalPerSlotAbove: 1,
      }),
      naturalStormBonus: {
        formula: "1d10",
        type: "fulmine",
        label: "Bonus manuale per tempesta naturale",
      },
      requiresParentInstance: true,
    },
  ],
  "gust-of-wind": [
    {
      id: "gust-of-wind-direction",
      label: "Cambia direzione",
      buttonLabel: "Cambia direzione",
      detail: "Azione bonus: riorienta la Folata di Vento.",
      economy: "bonus-action",
      resolutionKind: "zone-direction",
      subjectMode: "none",
      requiresTargets: false,
      requiresParentInstance: true,
      requiresZoneRoot: true,
      availableAfterCast: true,
      showInOverview: true,
      placementRuleId: "gust-of-wind:cast",
      rangeOrigin: "caster",
    },
  ],
  "xanathar-investitura-della-fiamma": [
    {
      id: "flame-investiture-line",
      label: "Linea di fuoco",
      buttonLabel: "Linea di fuoco",
      detail: "Azione: traccia una linea di fuoco lunga 4,5 m e larga 1,5 m adiacente al caster.",
      economy: "action",
      resolutionKind: "save-area",
      subjectMode: "none",
      requiresTargets: false,
      turnStartPrompt: true,
      availableAfterCast: true,
      placementRuleId: "xanathar-investitura-della-fiamma:linea-di-fuoco",
      rangeOrigin: "caster",
      save: { ability: "dex", onSuccess: "half" },
      damage: damage({
        formula: "4d8",
        type: "fuoco",
        onSave: "half",
      }),
      requiresParentInstance: true,
    },
  ],
  "xanathar-arma-sacra": [
    {
      id: "holy-weapon-dismiss",
      label: "Esplosione radiosa",
      buttonLabel: "Congeda Arma Sacra",
      detail: "Azione bonus: congeda l'arma e crea un'esplosione radiosa di raggio 9 m.",
      economy: "bonus-action",
      resolutionKind: "save-area",
      subjectMode: "none",
      requiresTargets: false,
      requiresParentInstance: true,
      requiresZoneRoot: false,
      availableAfterCast: true,
      placementRuleId: "xanathar-arma-sacra:burst",
      rangeOrigin: "caster",
      save: { ability: "con", onSuccess: "half" },
      damage: damage({
        formula: "4d8",
        type: "radiosi",
        onSave: "half",
      }),
      concentrationAction: "dismiss",
      failureEffects: [
        {
          id: "holy-weapon-blinded",
          kind: "debuff",
          label: "Accecato",
          detail: "Accecato per 1 minuto. Alla fine di ogni turno, TS Costituzione per terminare l'effetto.",
          expiry: { mode: "rounds", remaining: 10 },
          parentEffectId: "",
          manualRemoval: true,
          saveReminder: {
            ability: "con",
            timing: "turn-end",
            dcSource: "source-spell",
            label: "Se supera il TS, termina Accecato su di sé.",
          },
        },
      ],
    },
  ],
  "xanathar-sfera-della-tempesta": [
    {
      id: "storm-sphere-lightning",
      label: "Fulmine",
      buttonLabel: "Fulmine",
      detail: "Azione bonus: scegli una creatura entro 18 m dal centro della Sfera della Tempesta.",
      economy: "bonus-action",
      resolutionKind: "single-attack",
      subjectMode: "none",
      requiresTargets: false,
      turnStartPrompt: true,
      requiresZoneRoot: true,
      rangeOrigin: "root",
      range: { value: 18, unit: "m" },
      maxTargets: 1,
      attack: {
        outcomes: ["hit", "miss"],
        advantageWhen: "inside-root",
      },
      damage: damage({
        formula: "4d6",
        type: "fulmine",
        baseSlot: 4,
        additionalPerSlotAbove: 1,
      }),
      requiresParentInstance: true,
    },
  ],
});

export function getSpellActiveResolutionActions(spellId) {
  return SPELL_ACTIVE_RESOLUTION_ACTIONS[String(spellId || "").trim()] || [];
}
